# Generated by Django 2.2 on 2020-03-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOneTable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon_inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_prisoners', to='appOneTable.Dungeon')),
            ],
        ),
    ]
