# Generated by Django 2.2 on 2020-03-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='some notes here'),
            preserve_default=False,
        ),
    ]
