# Generated by Django 2.2 on 2020-03-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
